[pytest]
testpaths =
    ch01
    ch02
    ch03
    ch04
    ch05
    ch06
    ch07
    ch08
    ch09
    ch10
    ch11
    ch12
    ch13
    ch14
pythonpath =
    ch01/src
    ch02/src
    ch03/src
    ch04/src
    ch05/src
    ch06/src
    ch07/src
    ch08/src
    ch09/src
    ch10/src
    ch11/src
    ch12/src
    ch13/src
    ch14/src
python_files = test_*.py
python_functions = test_*
addopts = -v --tb=short
